---
# tasks file for turn

- name: import assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install turn
  ansible.builtin.package:
    name: "{{ turn_packages }}"
    state: present

- name: configure coturn
  ansible.builtin.template:
    src: turnserver.conf.j2
    dest: "{{ turn_configuration }}"
    mode: "0640"
  notify:
    - restart turn

- name: enable coturn
  ansible.builtin.lineinfile:
    path: /etc/default/coturn
    regexp: '^TURNSERVER_ENABLED='
    line: "TURNSERVER_ENABLED=1"
  when:
    - ansible_distribution_release == "bionic"

- name: ensure /etc/systemd/system/coturn.service.d exists
  ansible.builtin.file:
    path: /etc/systemd/system/coturn.service.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: place systemd override
  ansible.builtin.copy:
    src: override.conf
    dest: /etc/systemd/system/coturn.service.d/override.conf
    owner: root
    group: root
    mode: "0644"
  when:
    - ansible_os_family == "Debian"

- name: start turn
  ansible.builtin.service:
    name: "{{ turn_service }}"
    state: started
    enabled: yes
