---
#
# Ansible managed
#
repository:
  description: Install and configure gitlab-runner on your system.
  homepage: https://robertdebock.nl/
  topics: gitlabrunner, ansible, molecule, tox, playbook, hacktoberfest
