---
- name: 1.10 Ensure system-wide crypto policy is not legacy (Scored)
  package:
    name: crypto-policies-scripts
    state: present
  when:
    - cis_crypto_policy_not_legacy | bool

- name: 1.10 Ensure system-wide crypto policy is not legacy (Scored)
  lineinfile:
    path: /etc/crypto-policies/config
    mode: "0644"
    regexp: '^(?!#)(\S+)$'
    line: '{{ cis_crypto_policy }}'
    create: true
  notify:
    - update-crypto-policies
  when:
    - cis_crypto_policy_not_legacy | bool

# 1.11 Ensure system-wide crypto policy is FUTURE or FIPS (Scored)
# The commands to set FUTURE is similar to 1.10.
