---
# tasks file for powertools

- name: import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: enable powertools
  community.general.ini_file:
    path: "{{ ansible_distribution }}-powertools.repo"
    section: powertools
    option: enabled
    value: "1"
    mode: "0644"
  notify:
    - yum update cache
  when:
    - ansible_distribution in [ "CentOS", "EL", "Rocky", "AlmaLinux" ]
    - ansible_distribution_major_version >= "8"
