---
# tasks file for powertools

- name: enable powertools
  community.general.ini_file:
    path: /etc/yum.repos.d/CentOS-Linux-PowerTools.repo
    section: powertools
    option: enabled
    value: "1"
    mode: "0644"
  notify:
    - yum update cache
  when:
    - ansible_distribution in [ "CentOS", "EL" ]
    - ansible_distribution_major_version >= "8"
