---
# tasks file for gitlab_runner

- name: import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install requirements
  ansible.builtin.package:
    name: "{{ gitlab_runner_requirements }}"
    state: present

- name: get repository installation script
  ansible.builtin.get_url:
    url: "{{ gitlab_runner_script_url }}"
    dest: /tmp/gitlab-runner-script.sh
    mode: "750"

- name: run repository installation script
  ansible.builtin.command:
    cmd: /tmp/gitlab-runner-script.sh
    creates: "{{ gitlab_runner_repository_file }}"

- name: install gitlab-runner
  ansible.builtin.package:
    name: "{{ gitlab_runner_package }}"
    state: present

- name: register runner
  block:
    - name: get registration status
      ansible.builtin.command:
        cmd: gitlab-runner list
      register: gitlab_runner_get_registration_status
      changed_when: no

    - name: register gitlab runner
      ansible.builtin.command:
        cmd: >
          gitlab-runner register --non-interactive
          --name "{{ gitlab_runner_name }}"
          --url "{{ gitlab_runner_url }}"
          --registration-token "{{ gitlab_runner_token }}"
          --tag-list "{{ gitlab_runner_tags | join(',') }}"
          --executor "{{ gitlab_runner_executor }}"
          --docker-image "{{ gitlab_runner_docker_image }}"
          --locked="false"
      when:
        - gitlab_runner_name not in gitlab_runner_get_registration_status.stderr
  when:
    - gitlab_runner_token is defined

- name: start and enable gitlab-runner
  ansible.builtin.service:
    name: gitlab-runner
    state: started
    enabled: yes
