---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  vars_files: ../../vars/main.yml

  roles:
    - role: ansible-role-mysql
      mysql_users:
        - name: my_user
      mysql_databases:
        - name: my_db
          state: dump
          target: /tmp/my_db.mysql

  post_tasks:
    - name: try root account
      community.mysql.mysql_db:
        name: my_test
        state: present
        login_unix_socket: "{{ mysql_socket }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
