---
galaxy_info:
  author: Robert de Bock
  namespace: robertdebock
  role_name: vault
  description: Install Hashicorp Vault on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: "2.10"

  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Debian
      versions:
        - buster
    - name: Fedora
      versions:
        - 32
        - 33
    - name: Ubuntu
      versions:
        - bionic
        - focal

  galaxy_tags:
    - vault

dependencies: []
