---
project_name: Microsoft
reference: "https://github.com/robertdebock/ansible-role-omsagent/blob/master/defaults/main.yml"
versions:
  - name: OMS Agent for Linux GA
    url: "https://github.com/microsoft/OMS-Agent-for-Linux/releases"
