---
galaxy_info:
  author: Robert de Bock
  role_name: turn
  namespace: robertdebock
  description: Install and configure a (co) turn server on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: 2.9

  platforms:
    - name: Amazon
      versions:
        - Candidate
    - name: EL
      versions:
        - 7
        - 8
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - focal
        - bionic

  galaxy_tags:
    - turn

dependencies: []
