---
galaxy_info:
  author: Robert de Bock
  role_name: autofs
  description: Install and configure autofs on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: 2.8

  platforms:
    - name: Debian
      versions:
        - buster
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - focal
        - bionic

  galaxy_tags:
    - autofs

dependencies: []
