---
- name: 2.2.1.1 Ensure time synchronization is in use (Not Scored)
  command: rpm -q chrony
  args:
    warn: no
  register: cis_time_synchronization_test
  failed_when:
    - cis_time_synchronization_test.rc != 0
  when:
    - cis_time_synchronization | bool

- name: 2.2.1.2 Ensure chrony is configured (Scored)
  command: grep -E "^(server|pool)" /etc/chrony.conf
  register: cis_chrony_configured_test_one
  failed_when:
    cis_chrony_configured_test_one.stdout | length == 0
  when:
    - cis_chrony_configured | bool

- name: 2.2.1.2 Ensure chrony is configured (Scored)
  command: ps -ef | grep chrony[d]
  register: cis_chrony_configured_test_two
  failed_when:
    cis_chrony_configured_test_one.stdout | length == 0
  when:
    - cis_chrony_configured | bool

- name: 2.2.2 Ensure X Window System is not installed (Scored)
  command: rpm -qa --qf '%{NAME}\n' xorg-x11*
  args:
    warn: no
  register: cis_x_windows_system_not_installed_test_one
  when:
    - cis_x_windows_system_not_installed | bool

- name: 2.2.2 Ensure X Window System is not installed (Scored)
  package:
    name: "{{ item }}"
    state: absent
  check_mode: yes
  register: cis_x_windows_system_not_installed_test_two
  loop: "{{ cis_x_windows_system_not_installed_test_one.stdout_lines }}"
  failed_when:
    cis_x_windows_system_not_installed_test_two is changed
  when:
    - cis_x_windows_system_not_installed | bool

- name: 2.2.3 Ensure rsync service is not enabled (Scored)
  service:
    name: rsycnd
    state: stopped
    enabled: no
  check_mode: yes
  register: cis_rsync_service_not_enabled_test
  failed_when:
    - cis_rsync_service_not_enabled_test is changed
  when:
    - cis_rsync_service_not_enabled | bool
    - services["rsyncd.service"] is defined

- name: 2.2.4 Ensure Avahi Server is not enabled (Scored)
  service:
    name: avahi-daemon
    state: stopped
    enabled: no
  check_mode: yes
  register: cis_avahi_server_not_enabled_test
  failed_when:
    - cis_avahi_server_not_enabled_test is changed
  when:
    - cis_avahi_server_not_enabled | bool
    - services["avahi-daemon.service"] is defined

- name: 2.2.5 Ensure SNMP Server is not enabled (Scored)
  service:
    name: snmpd
    state: stopped
    enabled: no
  check_mode: yes
  register: cis_snmp_server_not_enabled_test
  failed_when:
    - cis_snmp_server_not_enabled_test is changed
  when:
    - cis_snmp_server_not_enabled | bool
    - services["snmpd.service"] is defined

- name: 2.2.6 Ensure HTTP Proxy Server is not enabled (Scored)
  service:
    name: squid
    state: stopped
    enabled: no
  check_mode: yes
  register: cis_http_proxy_server_not_enabled_test
  failed_when:
    - cis_http_proxy_server_not_enabled_test is changed
  when:
    - cis_http_proxy_server_not_enabled | bool
    - services["squid.service"] is defined

- name: 2.2.7 Ensure Samba is not enabled (Scored)
  service:
    name: smb
    state: stopped
    enabled: no
  check_mode: yes
  register: cis_samba_server_not_enabled_test
  failed_when:
    - cis_samba_server_not_enabled_test is changed
  when:
    - cis_samba_server_not_enabled | bool
    - services["smb.service"] is defined

- name: 2.2.8 Ensure IMAP and POP3 server is not enabled (Scored)
  service:
    name: dovecot
    state: stopped
    enabled: no
  check_mode: yes
  register: cis_imap_and_pop3_server_not_enabled_test
  failed_when:
    - cis_imap_and_pop3_server_not_enabled_test is changed
  when:
    - cis_imap_and_pop3_server_not_enabled | bool
    - services["dovecot.service"] is defined

- name: 2.2.9 Ensure HTTP server is not enabled (Scored)
  service:
    name: httpd
    state: stopped
    enabled: no
  check_mode: yes
  register: cis_http_server_not_enabled_test
  failed_when:
    - cis_http_server_not_enabled_test is changed
  when:
    - cis_http_server_not_enabled | bool
    - services["httpd.service"] is defined

- name: 2.2.10 Ensure FTP Server is not enabled (Scored)
  service:
    name: vsftpd
    state: stopped
    enabled: no
  check_mode: yes
  register: cis_ftp_server_not_enabled_test
  failed_when:
    - cis_ftp_server_not_enabled_test is changed
  when:
    - cis_ftp_server_not_enabled | bool
    - services["vsftpd.service"] is defined

- name: 2.2.11 Ensure DNS Server is not enabled (Scored)
  service:
    name: named
    state: stopped
    enabled: no
  check_mode: yes
  register: cis_dns_server_not_enabled_test
  failed_when:
    - cis_dns_server_not_enabled_test is changed
  when:
    - cis_dns_server_not_enabled | bool
    - services["named.service"] is defined

- name: 2.2.12 Ensure NFS is not enabled (Scored)
  service:
    name: nfs
    state: stopped
    enabled: no
  check_mode: yes
  register: cis_nfs_server_not_enabled_test
  failed_when:
    - cis_nfs_server_not_enabled_test is changed
  when:
    - cis_nfs_server_not_enabled | bool
    - services["nfs.service"] is defined

- name: 2.2.13 Ensure RPC is not enabled (Scored)
  service:
    name: rpcbind
    state: stopped
    enabled: no
  check_mode: yes
  register: cis_rpc_not_enabled_test
  failed_when:
    - cis_rpc_not_enabled_test is changed
  when:
    - cis_rpc_not_enabled | bool
    - services["rpcbind.service"] is defined

- name: 2.2.14 Ensure LDAP server is not enabled (Scored)
  service:
    name: slapd
    state: stopped
    enabled: no
  check_mode: yes
  register: cis_ldap_server_not_enabled_test
  failed_when:
    - cis_ldap_server_not_enabled_test is changed
  when:
    - cis_ldap_server_not_enabled | bool
    - services["slapd.service"] is defined

- name: 2.2.15 Ensure DHCP Server is not enabled (Scored)
  service:
    name: dhcpd
    state: stopped
    enabled: no
  check_mode: yes
  register: cis_dhcp_server_not_enabled_test
  failed_when:
    - cis_dhcp_server_not_enabled_test is changed
  when:
    - cis_dhcp_server_not_enabled | bool
    - services["dhcpd.service"] is defined

- name: 2.2.16 Ensure CUPS is not enabled (Scored)
  service:
    name: cups
    state: stopped
    enabled: no
  check_mode: yes
  register: cis_cups_not_enabled_test
  failed_when:
    - cis_cups_not_enabled_test is changed
  when:
    - cis_cups_not_enabled | bool
    - services["cups.service"] is defined

- name: 2.2.17 Ensure NIS Server is not enabled (Scored)
  service:
    name: ypserv
    state: stopped
    enabled: no
  check_mode: yes
  register: cis_nis_server_not_enabled_tets
  failed_when:
    - cis_nis_server_not_enabled_tets is changed
  when:
    - cis_nis_server_not_enabled | bool
    - services["ypserv.service"] is defined

- name: 2.2.18 Ensure mail transfer agent is configured for local-only mode (Scored)
  lineinfile:
    path: /etc/postfix/main.cf
    line: "inet_interfaces = loopback-only"
    regexp: '^inet_interfaces'
  check_mode: yes
  register: cis_mta_local_only_mode_test
  failed_when:
    - cis_mta_local_only_mode_test is changed
  when:
    - cis_mta_local_only_mode | bool
    - services["postfix.service"] is defined
