---
- name: 2.3.1 Ensure NIS Client is not installed (Scored)
  package:
    name: ypbind
    state: absent
  check_mode: yes
  register: cis_nis_client_not_installed_test
  failed_when:
    cis_nis_client_not_installed_test is changed
  when:
    - cis_nis_client_not_installed | bool

- name: 2.3.2 Ensure telnet client is not installed (Scored)
  package:
    name: telnet
    state: absent
  check_mode: yes
  register: cis_telnet_client_not_installed_test
  failed_when:
    cis_telnet_client_not_installed_test is changed
  when:
    - cis_telnet_client_not_installed | bool

- name: 2.3.3 Ensure LDAP client is not installed (Scored)
  package:
    name: openldap-clients
    state: absent
  check_mode: yes
  register: cis_ldap_client_not_installed_test
  failed_when:
    cis_ldap_client_not_installed_test is changed
  when:
    - cis_ldap_client_not_installed | bool
