---
# tasks file for nomachine

- name: include assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install nomachine
  ansible.builtin.package:
    name: "{{ nomachine_package }}"
    state: present
    disable_gpg_check: yes

- name: create nomachine service
  ansible.builtin.import_role:
    name: robertdebock.service
  vars:
    service_list:
      - name: nomachine
        description: NoMachine
        start_command: /etc/NX/nxserver --startup

- name: start and enable nomachine
  ansible.builtin.service:
    name: nomachine
    state: started
    enabled: yes
