---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: check docker-compose
      command: docker-compose --version
      environment:
        PATH: /bin:/usr/bin:/usr/local/bin
