---
#
# Ansible managed
#
repository:
  description: Install and configure Nomad.
  homepage: https://robertdebock.nl/
  topics: hashicorp, nomad, server, agent, cluster, ansible, molecule, tox, playbook, hacktoberfest
