---
# vars file for postgres

_postgres_packages:
  default:
    - postgresql-server
  Alpine:
    - postgresql
    - postgresql-dev
  Debian:
    - postgresql
    - postgresql-client

postgres_packages: "{{ _postgres_packages[ansible_os_family] | default(_postgres_packages['default']) }}"

_postgres_dir:
  default: /var/lib/pgsql/data
  Alpine: /var/lib/pgsql
  Debian: /var/lib/postgresql/11

postgres_dir: "{{ _postgres_dir[ansible_os_family] | default(_postgres_dir['default']) }}"

_postgres_conf_dir:
  default: "{{ postgres_dir }}"
  Debian: /etc/postgresql/11/main

postgres_conf_dir: "{{ _postgres_conf_dir[ansible_os_family] | default(_postgres_conf_dir['default']) }}"
