---
# tasks file for cis

- name: include assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

# For now, only collect service_facts on non-Ubuntu due to:
# https://github.com/ansible/ansible/issues/71140
# - name: populate service facts
#   ansible.builtin.service_facts:

- name: gather the rpm package facts
  ansible.builtin.package_facts:

- name: include distribution specific version
  ansible.builtin.include: "{{ ansible_distribution ~ '-' ~ ansible_distribution_major_version }}/main.yml"
