---
# tasks file for lxc

- name: include assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install lxc
  ansible.builtin.package:
    name: "{{ lxc_packages }}"
    state: present

- name: enable lxc bridge
  lineinfile:
    path: /etc/sysconfig/lxc
    regexp: '^USE_LXC_BRIDGE='
    line: 'USE_LXC_BRIDGE="true"'
  notify:
    - restart lxc-net

- name: start lxc services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ lxc_services }}"

- name: start lxc containers
  community.general.lxc_container:
    name: "{{ item.name }}"
    container_log: "{{ item.container_log | default(omit) }}"
    template: "{{ item.template | default('ubuntu') }}"
    state: "{{ item.state | default('started') }}"
    template_options: "{{ item.template_options | default(omit) }}"
  loop: "{{ lxc_containers }}"
  when:
    - lxc_containers is defined
