---
roles:
  - name: robertdebock.bootstrap
  - name: robertdebock.buildtools
  - name: robertdebock.cron
  - name: robertdebock.core_dependencies
  - name: robertdebock.epel
  - name: robertdebock.httpd
  - name: robertdebock.mysql
  - name: robertdebock.openssl
  - name: robertdebock.php
  - name: robertdebock.python_pip
  - name: robertdebock.selinux
