---
- name: 3.2.1 Ensure source routed packets are not accepted (Scored)
  sysctl:
    name: net.ipv4.conf.all.accept_source_route
    value: "0"
    state: present
  check_mode: yes
  register: cis_source_routed_packets_not_accepted_test_one
  failed_when:
    - cis_source_routed_packets_not_accepted_test_one is changed
  when:
    - cis_source_routed_packets_not_accepted | bool

- name: 3.2.1 Ensure source routed packets are not accepted (Scored)
  sysctl:
    name: net.ipv4.conf.default.accept_source_route
    value: "0"
    state: present
  check_mode: yes
  register: cis_source_routed_packets_not_accepted_test_two
  failed_when:
    - cis_source_routed_packets_not_accepted_test_two is changed
  when:
    - cis_source_routed_packets_not_accepted | bool

- name: 3.2.1 Ensure source routed packets are not accepted (Scored)
  sysctl:
    name: net.ipv6.conf.all.accept_source_route
    value: "0"
    state: present
  check_mode: yes
  register: cis_source_routed_packets_not_accepted_test_three
  failed_when:
    - cis_source_routed_packets_not_accepted_test_three is changed
  when:
    - cis_source_routed_packets_not_accepted | bool

- name: 3.2.1 Ensure source routed packets are not accepted (Scored)
  sysctl:
    name: net.ipv6.conf.default.accept_source_route
    value: "0"
    state: present
  check_mode: yes
  register: cis_source_routed_packets_not_accepted_test_four
  failed_when:
    - cis_source_routed_packets_not_accepted_test_four is changed
  when:
    - cis_source_routed_packets_not_accepted | bool

- name: 3.2.2 Ensure ICMP redirects are not accepted (Scored)
  sysctl:
    name: net.ipv4.conf.all.accept_redirects
    value: "0"
    state: present
  check_mode: yes
  register: cis_icmp_redirects_not_accepted_test_one
  failed_when:
    - cis_icmp_redirects_not_accepted_test_one is changed
  when:
    - cis_icmp_redirects_not_accepted | bool

- name: 3.2.2 Ensure ICMP redirects are not accepted (Scored)
  sysctl:
    name: net.ipv4.conf.default.accept_redirects
    value: "0"
    state: present
  check_mode: yes
  register: cis_icmp_redirects_not_accepted_test_two
  failed_when:
    - cis_icmp_redirects_not_accepted_test_two is changed
  when:
    - cis_icmp_redirects_not_accepted | bool

- name: 3.2.2 Ensure ICMP redirects are not accepted (Scored)
  sysctl:
    name: net.ipv6.conf.all.accept_redirects
    value: "0"
    state: present
  check_mode: yes
  register: cis_icmp_redirects_not_accepted_test_three
  failed_when:
    - cis_icmp_redirects_not_accepted_test_three is changed
  when:
    - cis_icmp_redirects_not_accepted | bool

- name: 3.2.2 Ensure ICMP redirects are not accepted (Scored)
  sysctl:
    name: net.ipv6.conf.default.accept_redirects
    value: "0"
    state: present
  check_mode: yes
  register: cis_icmp_redirects_not_accepted_test_four
  failed_when:
    - cis_icmp_redirects_not_accepted_test_four is changed
  when:
    - cis_icmp_redirects_not_accepted | bool

- name: 3.2.3 Ensure secure ICMP redirects are not accepted (Scored)
  sysctl:
    name: net.ipv4.conf.all.secure_redirects
    value: "0"
    state: present
  check_mode: yes
  register: cis_secure_icmp_redirects_not_accepted_test_one
  failed_when:
    - cis_secure_icmp_redirects_not_accepted_test_one is changed
  when:
    - cis_secure_icmp_redirects_not_accepted | bool

- name: 3.2.3 Ensure secure ICMP redirects are not accepted (Scored)
  sysctl:
    name: net.ipv4.conf.default.secure_redirects
    value: "0"
    state: present
  check_mode: yes
  register: cis_secure_icmp_redirects_not_accepted_test_two
  failed_when:
    - cis_secure_icmp_redirects_not_accepted_test_two is changed
  when:
    - cis_secure_icmp_redirects_not_accepted | bool

- name: 3.2.4 Ensure suspicious packets are logged (Scored)
  sysctl:
    name: net.ipv4.conf.all.log_martians
    value: "1"
    state: present
  check_mode: yes
  register: cis_suspicious_packets_logged_test_one
  failed_when:
    - cis_suspicious_packets_logged_test_one is changed
  when:
    - cis_suspicious_packets_logged | bool

- name: 3.2.4 Ensure suspicious packets are logged (Scored)
  sysctl:
    name: net.ipv4.conf.default.log_martians
    value: "1"
    state: present
  check_mode: yes
  register: cis_suspicious_packets_logged_test_two
  failed_when:
    - cis_suspicious_packets_logged_test_two is changed
  when:
    - cis_suspicious_packets_logged | bool

- name: 3.2.5 Ensure broadcast ICMP requests are ignored (Scored)
  sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: "1"
    state: present
  check_mode: yes
  register: cis_broadcast_icmp_requests_ignored_test
  failed_when:
    - cis_broadcast_icmp_requests_ignored_test is changed
  when:
    - cis_broadcast_icmp_requests_ignored | bool

- name: 3.2.6 Ensure bogus ICMP responses are ignored (Scored)
  sysctl:
    name: net.ipv4.icmp_ignore_bogus_error_responses
    value: "1"
    state: present
  check_mode: yes
  register: cis_bogus_icmp_responses_ignored
  failed_when:
    - cis_bogus_icmp_responses_ignored is changed
  when:
    - cis_bogus_icmp_responses_ignored | bool

- name: 3.2.7 Ensure Reverse Path Filtering is enabled (Scored)
  sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: "1"
    state: present
  check_mode: yes
  register: cis_reverse_path_filtering_test_one
  failed_when:
    - cis_reverse_path_filtering_test_one is changed
  when:
    - cis_reverse_path_filtering | bool

- name: 3.2.7 Ensure Reverse Path Filtering is enabled (Scored)
  sysctl:
    name: net.ipv4.conf.default.rp_filter
    value: "1"
    state: present
  check_mode: yes
  register: cis_reverse_path_filtering_test_two
  failed_when:
    - cis_reverse_path_filtering_test_two is changed
  when:
    - cis_reverse_path_filtering | bool

- name: 3.2.8 Ensure TCP SYN Cookies is enabled (Scored)
  sysctl:
    name: net.ipv4.tcp_syncookies
    value: "1"
    state: present
  check_mode: yes
  register: cis_tcp_syn_cookies_enabled_test
  failed_when:
    - cis_tcp_syn_cookies_enabled_test is changed
  when:
    - cis_tcp_syn_cookies_enabled | bool

- name: 3.2.9 Ensure IPv6 router advertisements are not accepted (Scored)
  sysctl:
    name: net.ipv6.conf.all.accept_ra
    value: "0"
    state: present
  check_mode: yes
  register: cis_ipv6_router_advertisements_not_accepted_test_one
  failed_when:
    - cis_ipv6_router_advertisements_not_accepted_test_one is changed
  when:
    - cis_ipv6_router_advertisements_not_accepted | bool

- name: 3.2.9 Ensure IPv6 router advertisements are not accepted (Scored)
  sysctl:
    name: net.ipv6.conf.default.accept_ra
    value: "0"
    state: present
  check_mode: yes
  register: cis_ipv6_router_advertisements_not_accepted_test_two
  failed_when:
    - cis_ipv6_router_advertisements_not_accepted_test_two is changed
  when:
    - cis_ipv6_router_advertisements_not_accepted | bool
