---
- name: 3.6 Disable IPv6 (Not Scored)
  replace:
    path: /boot/grub2/grubenv
    regexp: '^kernelopts="((:?(?!ipv6\.disable=1).)*?)"$'
    replace: 'kernelopts="\1 ipv6.disable=1"'
  check_mode: yes
  register: cis_disable_ipv6_test
  failed_when:
    - cis_disable_ipv6_test is changed
  when:
    - cis_disable_ipv6 | bool
