---
# handlers file for dnsmasq

- name: Test dnsmasq configuration
  ansible.builtin.command:
    cmd: dnsmasq --test

- name: Restart dnsmasq
  ansible.builtin.service:
    name: "{{ dnsmasq_service }}"
    state: restarted
  when:
    - not ansible_check_mode
