---
# handlers file for dnsmasq

- name: test dnsmasq configuration
  ansible.builtin.command: dnsmasq --test

- name: restart dnsmasq
  ansible.builtin.service:
    name: "{{ dnsmasq_service }}"
    state: restarted
  when:
    - not ansible_check_mode | bool
