---
# tasks file for jenkins

- name: import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: add yum repository
  ansible.builtin.get_url:
    url: "{{ jenkins_yum_repository_baseurl }}"
    dest: /etc/yum.repos.d/jenkins.repo
    validate_certs: no
    mode: "0644"
  when:
    - ansible_pkg_mgr in [ "dnf", "yum" ]

- name: import rpm key
  ansible.builtin.rpm_key:
    key: "{{ jenkins_rpm_key }}"
    state: present
    validate_certs: no
  when:
    - ansible_pkg_mgr in [ "dnf", "yum", "zypper" ]

- name: configure apt
  block:
    - name: add apt key
      ansible.builtin.apt_key:
        url: "{{ jenkins_apt_key_url }}"
        state: present

    - name: add apt repository
      ansible.builtin.apt_repository:
        repo: "{{ jenkins_apt_repository_repo }}"
        state: present
  when:
    - ansible_pkg_mgr == "apt"

- name: add zypper repository
  community.general.zypper_repository:
    name: jenkins
    repo: "{{ jenkins_zypper_repository_repo }}"
    state: present
  when:
    - ansible_pkg_mgr == "zypper"

- name: install requirements
  ansible.builtin.package:
    name: "{{ jenkins_requirements }}"
    state: present

- name: install jenkins (specific version)
  ansible.builtin.package:
    name: "{{ jenkins_package }}"
    state: present
  when:
    - jenkins_version is defined

- name: install jenkins
  ansible.builtin.package:
    name: jenkins
    state: present
  when:
    - jenkins_version is not defined

- name: configure jenkins
  ansible.builtin.template:
    src: jenkins.j2
    dest: "{{ jenkins_configuration_directory }}"
    mode: "0640"
  notify:
    - restart jenkins

- name: manage jenkins service
  ansible.builtin.service:
    name: jenkins
    state: started
    enabled: yes
