---
# tasks file for vault

- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: Run shared tasks
  ansible.builtin.include_tasks:
    file: shared.yml

- name: Run leader tasks
  ansible.builtin.include_tasks:
    file: leader.yml

- name: Run follower tasks
  ansible.builtin.include_tasks:
    file: follower.yml
  when:
    - not ansible_check_mode
    - inventory_hostname != vault_leader

- name: Run provisioning tasks
  ansible.builtin.include_tasks:
    file: provisioning.yml
  when:
    - vault_kv_secrets is defined
    - vault_root_token is defined or
      vault_init_output.root_token is defined
