---
# tasks file for vault

- name: import assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: run shared tasks
  ansible.builtin.include_tasks: shared.yml

- name: run leader tasks
  ansible.builtin.include_tasks: leader.yml

- name: run follower tasks
  ansible.builtin.include_tasks: follower.yml
  when:
    - not ansible_check_mode | bool
    - inventory_hostname != vault_leader

- name: run provisioning tasks
  ansible.builtin.include_tasks: provisioning.yml
  when:
    - vault_kv_secrets is defined
    - vault_root_token is defined or
      vault_init_output.root_token is defined
