---
- name: converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-mount
      mount_requests:
        - path: /mnt/tmp
          src: /tmp
          opts: bind
          state: mounted
          fstype: none
          mode: "1777"
