---
# tasks file for forensics

- name: include assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: create {{ forensics_local_storage_path }}/{{ inventory_hostname_short }}
  ansible.builtin.file:
    path: "{{ forensics_local_storage_path }}/{{ inventory_hostname_short }}"
    state: directory
    mode: "700"

- name: collect files in directories
  ansible.builtin.include_tasks: directory_collector.yml
  loop: "{{ forensics_directory_list }}"
  loop_control:
    loop_var: object

- name: collect files
  ansible.builtin.include_tasks: file_collector.yml
  loop: "{{ forensics_file_list }}"
  loop_control:
    loop_var: object

- name: collect command output
  ansible.builtin.include_tasks: command_collector.yml
  loop: "{{ forensics_command_list }}"
  loop_control:
    loop_var: object

- name: collect specific files in directories
  ansible.builtin.include_tasks: specific_file_collector.yml
  loop: "{{ forensics_specific_file_list }}"
  loop_control:
    loop_var: object
