---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: check if connection still works
      ansible.builtin.ping:

    - name: check if ports responds
      ansible.builtin.wait_for:
        port: "{{ item }}"
      loop:
        - 80
        - 443

    - name: check of content can be retrieved
      ansible.builtin.uri:
        url: "{{ item }}"
        validate_certs: no
        status_code:
          - 200
          - 403
      loop:
        - "http://localhost/"
        - "https://localhost/"
