---
galaxy_info:
  author: Robert de Bock
  role_name: gitlab_runner
  description: Install and configure gitlab-runner on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: "2.10"

  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Debian
      versions:
        - buster
    - name: Ubuntu
      versions:
        - focal
        - bionic

  galaxy_tags:
    - gitlabrunner

dependencies: []
