---
# tasks file for minikube

- name: include assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install requirements
  ansible.builtin.package:
    name: "{{ minikube_requirements }}"
    state: present

- name: install minikube (apt)
  ansible.builtin.apt:
    deb: "{{ item }}"
    state: present
  when:
    - ansible_os_family == "Debian"
  loop: "{{ minikube_packages }}"

- name: install minikube (yum)
  ansible.builtin.yum:
    name: "{{ minikube_packages }}"
    state: present
    disable_gpg_check: yes
  when:
    - ansible_os_family == "RedHat"

- name: start minikube once
  ansible.builtin.command: "{{ minikube_command }}"
  args:
    creates: nothing
  when:
    - ansible_connection != "docker"
