---
# tasks file for openssl

- name: include assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install pip packages
  ansible.builtin.pip:
    name: "{{ openssl_pip_packages }}"

- name: create key directory
  ansible.builtin.file:
    path: "{{ openssl_key_directory }}"
    state: directory
    mode: "750"
    owner: root
    group: root

- name: create csr directory
  ansible.builtin.file:
    path: "{{ openssl_csr_directory }}"
    state: directory
    mode: "755"
    owner: root
    group: root

- name: create crt directory
  ansible.builtin.file:
    path: "{{ openssl_crt_directory }}"
    state: directory
    mode: "755"
    owner: root
    group: root

- name: include create.yml
  ansible.builtin.include_tasks: create.yml
  loop: "{{ openssl_items }}"
  when:
    - openssl_items is defined
    - openssl_items | length > 0
