---
galaxy_info:
  author: robertdebock
  role_name: vault_configuration
  description: Configure HashiCorp Vault.
  license: Apache-2.0
  company: none
  min_ansible_version: "2.10"

  platforms:
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - focal
        - bionic

  galaxy_tags:
    - vaultconfiguration
    - hashicorp

dependencies: []
