---
galaxy_info:
  author: Robert de Bock
  role_name: vault_configuration
  namespace: robertdebock
  description: Configure HashiCorp Vault.
  license: Apache-2.0
  company: none
  min_ansible_version: 2.9

  platforms:
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - 34
        - 35
    - name: Ubuntu
      versions:
        - focal
        - bionic

  galaxy_tags:
    - vaultconfiguration
    - hashicorp

dependencies: []
