---

- name: test if artifactory_file_store_dir is set correctly
  ansible.builtin.assert:
    that:
      - artifactory_file_store_dir is defined
      - artifactory_file_store_dir is string
    quiet: yes
