---
- name: 1.7.1.1 Ensure SELinux is installed (Scored)
  package:
    name: libselinux
    state: present
  register: cis_selinux_installed_test
  check_mode: yes
  when:
    - cis_selinux_installed

- name: 1.7.1.1 Ensure SELinux is installed (Scored)
  assert:
    that:
      - cis_selinux_installed_test is not changed
    quiet: yes
  when:
    - cis_selinux_installed

- name: 1.7.1.2 Ensure SELinux is not disabled in bootloader configuration (Scored)
  command: grep -E 'kernelopts=(\S+\s+)*(selinux=0|enforcing=0)+\b' /boot/grub2/grubenv
  register: cis_selinux_not_disabled_test
  when:
    - cis_selinux_not_disabled

- name: 1.7.1.2 Ensure SELinux is not disabled in bootloader configuration (Scored)
  assert:
    that:
      - cis_selinux_not_disabled_test.stdout | length == 0
    quiet: yes
  when:
    - cis_selinux_not_disabled

- name: 1.7.1.3 Ensure SELinux policy is configured (Scored)
  command: grep -E '^\s*SELINUXTYPE=(targeted|mls)\b' /etc/selinux/config
  register: cis_selinux_policy_configured_test_one
  when:
    - cis_selinux_policy_configured

- name: 1.7.1.3 Ensure SELinux policy is configured (Scored)
  assert:
    that:
      - cis_selinux_policy_configured_test_one.stdout in ["SELINUXTYPE=targeted", "SELINUXTYPE=mls"]
    quiet: yes
  when:
    - cis_selinux_policy_configured

- name: 1.7.1.3 Ensure SELinux policy is configured (Scored)
  shell: set -o pipefail && sestatus | grep Loaded
  register: cis_selinux_policy_configured_test_two
  when:
    - cis_selinux_policy_configured

- name: 1.7.1.3 Ensure SELinux policy is configured (Scored)
  assert:
    that:
      - cis_selinux_policy_configured_test_two.stdout in ["targeted", "mls"]
    quiet: yes
  when:
    - cis_selinux_policy_configured

- name: 1.7.1.4 Ensure the SELinux state is enforcing (Scored)
  command: grep -E '^\s*SELINUX=enforcing' /etc/selinux/config
  register: cis_selinux_state_enforcing_test_one
  when:
    - cis_selinux_state_enforcing

- name: 1.7.1.4 Ensure the SELinux state is enforcing (Scored)
  assert:
    that:
      - cis_selinux_state_enforcing_test_one.stdout == "SELINUX=enforcing"
  when:
    - cis_selinux_state_enforcing

- name: 1.7.1.4 Ensure the SELinux state is enforcing (Scored)
  command: sestatus | grep "SELinux status:"
  register: cis_selinux_state_enforcing_test_two
  when:
    - cis_selinux_state_enforcing

- name: 1.7.1.4 Ensure the SELinux state is enforcing (Scored)
  assert:
    that:
      - cis_selinux_state_enforcing_test_two.stdout == "SELinux status: enabled"
  when:
    - cis_selinux_state_enforcing

- name: 1.7.1.5 Ensure no unconfined services exist (Scored)
  command: ps -eZ | grep unconfined_service_t
  args:
    warn: no
  register: cis_no_unconfined_services_test
  failed_when:
    - cis_no_unconfined_services_test.stdout | length > 0
  when:
    - cis_no_unconfined_services

- name: 1.7.1.6 Ensure SETroubleshoot is not installed (Scored)
  command: rpm -q setroubleshoot
  args:
    warn: no
  register: cis_setroubleshoot_not_installed_test
  failed_when:
    - cis_setroubleshoot_not_installed_test.rc == 0
  when:
    - cis_setroubleshoot_not_installed

- name: 1.7.1.7 Ensure the MCS Translation Service (mcstrans) is not installed (Scored)
  command: rpm -q mcstrans
  args:
    warn: no
  register: cis_mcs_translation_service_not_installed_test
  failed_when:
    - cis_mcs_translation_service_not_installed_test.rc == 0
  when:
    - cis_mcs_translation_service_not_installed
