---
- name: 1.8.1.1 Ensure message of the day is configured properly (Scored)
  copy:
    content: "{{ cis_message_of_the_day }}"
    dest: /etc/motd
  check_mode: yes
  register: cis_message_of_the_day_configured_test_one
  failed_when:
    - cis_message_of_the_day_configured_test_one is changed
  when:
    - cis_message_of_the_day_configured | bool

# - name: 1.8.1.1 Ensure message of the day is configured properly (Scored)
#   command: grep -E -i "(\\\v|\\\r|\\\m|\\\s|$(grep '^ID=' /etc/os-release | cut -d= -f2 | sed -e 's/"//g'))" /etc/motd
#   check_mode: yes
#   register: cis_message_of_the_day_configured_test_two
#   failed_when:
#     - cis_message_of_the_day_configured_test_two.stdout | length > 0
#   when:
#     - cis_message_of_the_day_configured | bool

- name: 1.8.1.2 Ensure local login warning banner is configured properly (Scored)
  copy:
    content: "{{ cis_message_of_the_day }}"
    dest: /etc/issue
  check_mode: yes
  register: cis_local_login_banner_configured_test_one
  failed_when:
    - cis_local_login_banner_configured_test_one is changed
  when:
    - cis_local_login_banner_configured | bool

# - name: 1.8.1.2 Ensure local login warning banner is configured properly (Scored)
#   command: grep -E -i "(\\\v|\\\r|\\\m|\\\s|$(grep '^ID=' /etc/os-release | cut -d= -f2 | sed -e 's/"//g'))" /etc/issue
#   check_mode: yes
#   register: cis_local_login_banner_configured_test_two
#   failed_when:
#     - cis_local_login_banner_configured_test_two.stdout | length > 0
#   when:
#     - cis_local_login_banner_configured | bool

- name: 1.8.1.3 Ensure remote login warning banner is configured properly (Scored)
  copy:
    content: "{{ cis_message_of_the_day }}"
    dest: /etc/issue.net
  check_mode: yes
  register: cis_remote_login_banner_configured_test_one
  failed_when:
    - cis_remote_login_banner_configured_test_one is changed
  when:
    - cis_remote_login_banner_configured | bool

- name: 1.8.1.4 Ensure permissions on /etc/motd are configured (Scored)
  stat:
    path: /etc/motd
  register: cis_permissions_etc_motd_test
  when:
    - cis_permissions_etc_motd | bool

- name: 1.8.1.4 Ensure permissions on /etc/motd are configured (Scored)
  assert:
    that:
      - cis_permissions_etc_motd_test.stat.mode == "0644"
      - cis_permissions_etc_motd_test.stat.gid == 0
      - cis_permissions_etc_motd_test.stat.uid == 0
    quiet: yes
  when:
    - cis_permissions_etc_motd | bool

- name: 1.8.1.5 Ensure permissions on /etc/issue are configured (Scored)
  stat:
    path: /etc/issue
  register: cis_permissions_etc_issue_test
  when:
    - cis_permissions_etc_issue | bool

- name: 1.8.1.5 Ensure permissions on /etc/issue are configured (Scored)
  assert:
    that:
      - cis_permissions_etc_issue_test.stat.mode == "0644"
      - cis_permissions_etc_issue_test.stat.gid == 0
      - cis_permissions_etc_issue_test.stat.uid == 0
    quiet: yes
  when:
    - cis_permissions_etc_issue | bool

- name: 1.8.1.6 Ensure permissions on /etc/issue.net are configured (Scored)
  stat:
    path: /etc/issue.net
  register: cis_permissions_etc_issue_net_test
  when:
    - cis_permissions_etc_issue_net | bool

- name: 1.8.1.6 Ensure permissions on /etc/issue.net are configured (Scored)
  assert:
    that:
      - cis_permissions_etc_issue_net_test.stat.mode == "0644"
      - cis_permissions_etc_issue_net_test.stat.gid == 0
      - cis_permissions_etc_issue_net_test.stat.uid == 0
    quiet: yes
  when:
    - cis_permissions_etc_issue_net | bool

- name: 1.8.2 Ensure GDM login banner is configured (Scored)
  package_facts:
  when:
    - cis_gdm_login_banner_configured | bool

- name: 1.8.2 Ensure GDM login banner is configured (Scored)
  lineinfile:
    path: /etc/gdm3/greeter.dconf-defaults
    section: org/gnome/login-screen
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  check_mode: yes
  register: cis_gdm_login_banner_configured_test
  loop:
    - option: banner-message-enable
      value: "true"
    - option: banner-message-text
      value: "{{ cis_message_of_the_day }}"
  loop_control:
    label: "{{ item.option }}"
  when:
    - cis_gdm_login_banner_configured | bool
    - "'gdm' in ansible_facts.packages"

- name: 1.8.2 Ensure GDM login banner is configured (Scored)
  assert:
    that:
      - item is not changed
    quiet: yes
  loop: "{{ cis_gdm_login_banner_configured_test.results }}"
  loop_control:
    label: "{{ item.item.option }}"
  when:
    - cis_gdm_login_banner_configured | bool
