---

name: Build and Deploy Collection

on:
  push:

jobs:
  deploy:
    runs-on: "Ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Ansible Galaxy Collection
        uses: artis3n/ansible_galaxy_collection@v2.4.4
        with:
          api_key: '${{ secrets.GALAXY_API_KEY }}'
